### ISSUE TITLE
Couldn't find @openzeppelin/contracts/...

### ISSUE THREAD

**Issue by magnetto90** [defi-wonderland/natspec-smells#24] opened 2024-01-29 15:26 UTC
When executing the tool I am getting the following error msg.

```bash
❯ yarn natspec-smells
yarn run v1.22.19
$ /home/whitehat/project/node_modules/.bin/natspec-smells
CompileInferenceError: Couldn't find @openzeppelin/contracts/utils/math/SignedMath.sol
    at findAllFiles (/home/whitehat/project/node_modules/solc-typed-ast/dist/compile/inference/imports.js:113:23)
    at async compileSol (/home/whitehat/project/node_modules/solc-typed-ast/dist/compile/utils.js:160:9)
    at async getProjectCompiledSources (/home/whitehat/project/node_modules/@defi-wonderland/natspec-smells/lib/utils.js:29:27)
    at async /home/whitehat/project/node_modules/@defi-wonderland/natspec-smells/lib/main.js:16:25
```

I am also especifing the remappings inside `foundry.toml`

```toml
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/",
    "v3-core/=lib/v3-core/contracts/"
]
```

**Comment by gas1cent** [comment] 2024-01-29 15:29
@magnetto90 any chance we can see the code and try to reproduce the issue?

**Comment by magnetto90** [comment] 2024-01-29 15:51
> @magnetto90 any chance we can see the code and try to reproduce the issue?

@gas1cent sure, I am working in this [project/tree](https://github.com/overlay-market/v1-core/tree/staging)

**Comment by gas1cent** [comment] 2024-01-29 16:23
@magnetto90 thanks! Try to put this into a `remappings.txt` file and let me know if it helps:
```
@openzeppelin/=lib/openzeppelin-contracts/
@chainlink/=lib/chainlink/
v3-core/=lib/v3-core/contracts/
```
The issue is essentially due to the tool looking for remappings in the wrong place. We will fix that asap.

**Comment by magnetto90** [comment] 2024-01-29 16:38
@gas1cent Works! Some feedback...

1. Consider that latest version of foundry doesn´t need `remappings.txt` for common libraries such as OZ or Solady.
2. In my case the extension of the result of running the tool, since we weren't using natspec, is too long, maybe is a good idea to add an `output file` option in the config file.

**Comment by gas1cent** [comment] 2024-01-29 16:40
Appreciate the feedback 👍🏻
I'm closing this issue since it's resolved, but feel free to open a new one if you find something else.

**Closed by gas1cent** 2024-01-29 16:40 UTC
